const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const jwt = require('jsonwebtoken');
const db = require('../db');
const responseHandler = require('../utils/responseHandler');
const VerifyUserToken = require('../middleware/VerifyUserToken');

const router = express.Router();

const storage = multer.diskStorage({
    destination: (req, file, cb) => {
        const tempDir = path.join(__dirname, '../ImageView');
        if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir, { recursive: true });
        }
        cb(null, tempDir);
    },
    filename: (req, file, cb) => {
        var filename = file.originalname.replace(/ /g, "%20")
        cb(null, `${Date.now()}-${filename}`);
    }
});

const upload = multer({ storage });

router.post('/get_image', (req, res) => {
    const { type } = req.query;
    if (type === 'banner') {
        const sql = 'SELECT image FROM images ORDER BY id ASC LIMIT 5';
        db.query(sql, (err, data) => {
            if (err) {
                console.error("Database error:", err);
                return res.status(500).json(responseHandler("Failure", 500, "Internal Server Error"));
            }
            res.status(200).json(responseHandler("Success", 200, "Images Fetched successfully", data));
        });
    }
    else if (type === 'view') {
        const sql = 'SELECT image FROM images';
        db.query(sql, (err, data) => {
            if (err) {
                console.error("Database error:", err);
                return res.status(500).json(responseHandler("Failure", 500, "Internal Server Error"));
            }
            res.status(200).json(responseHandler("Success", 200, "Images Fetched successfully", data));
        });
    }
    else {
        return res.status(400).json(responseHandler("Alert", 400, "Invalid type"));
    }
});

router.post('/post_image', VerifyUserToken, upload.single('document'), (req, res) => {
    // const { type } = req.body;

    if (!req.file) {
        return res.status(400).json(responseHandler("Alert", 400, "Image is required"));
    }

    const sql = `INSERT INTO images (image) VALUES (?)`;

    const fileName = req.file.filename; // Name generated by multer

    db.query(sql, [fileName], (err, data) => {
        if (err) {
            console.error("Database error:", err);
            return res.status(500).json(responseHandler("Failure", 500, "Internal Server Error"));
        }

        const imageId = data.insertId;
        const imageDir = path.join(__dirname, '../imageview', String(imageId));
        if (!fs.existsSync(imageDir)) {
            fs.mkdirSync(imageDir, { recursive: true });
        }

        const newFilePath = path.join(imageDir, req.file.originalname);
        fs.rename(req.file.path, newFilePath, (renameErr) => {
            if (renameErr) {
                console.error("File rename error:", renameErr);
                return res.status(500).json(responseHandler("Failure", 500, "Error moving image"));
            }

            let relativeFilePath = path.join('imageview', String(imageId), req.file.originalname);
            relativeFilePath = relativeFilePath.replace(/ /g, '%20'); // Replace spaces with %20
            const updateSql = 'UPDATE images SET image = ? WHERE id = ?';
            db.query(updateSql, [`https://sakhi-empowerment.in/${relativeFilePath}`, imageId], (updateErr) => {
                if (updateErr) {
                    console.error("Database update error:", updateErr);
                    return res.status(500).json(responseHandler("Failure", 500, "Error updating image path"));
                }

                res.status(201).json(responseHandler("Success", 201, "Scheme added successfully", { image: 'https://sakhi-empowerment.in/' + relativeFilePath }));
            });
        });
    });
});

router.delete('/delete_image', VerifyUserToken, (req, res) => {
    const { id } = req.query;
    // Check if the Image exists and retrieve the document URL
    const sqlSelect = 'SELECT image FROM images WHERE id = ?';
    db.query(sqlSelect, [schemeId], (err, result) => {
        if (err) {
            console.error("Database error:", err);
            return res.status(500).json(responseHandler("Failure", 500, "Internal Server Error"));
        }

        if (result.length === 0) {
            return res.status(404).json(responseHandler("Not Found", 404, "Image ID not found"));
        }

        const documentUrl = result[0].document_url;

        // Construct the folder path
        const imageDir = path.join(__dirname, '../imageview', String(id));

        // Delete the scheme data from the database
        const sqlDelete = 'DELETE FROM images WHERE id = ?';
        db.query(sqlDelete, [id], (deleteErr) => {
            if (deleteErr) {
                console.error("Database error during deletion:", deleteErr);
                return res.status(500).json(responseHandler("Failure", 500, "Error deleting image from database"));
            }

            // Delete the folder containing the document
            fs.rm(imageDir, { recursive: true, force: true }, (fsErr) => {
                if (fsErr) {
                    console.error("File system error during folder deletion:", fsErr);
                    return res.status(500).json(responseHandler("Failure", 500, "Error deleting image folder"));
                }

                res.status(200).json(responseHandler("Success", 200, "Image deleted successfully"));
            });
        });
    });
});

module.exports = router;